global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: 'boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - boot-app-host:8080
        - boot-app-host2:8081
    relabel_configs:
        - source_labels: ['job']
          target_label: application

  - job_name: 'boot-app2'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - boot-app2-host:8083
    relabel_configs:
        - source_labels: ['job']
          target_label: application
