version: "3"
services:
  volumes-provisioner: # for prometheus /data folder rights
    image: hasnat/volumes-provisioner:latest
    environment:
      PROVISION_DIRECTORIES: "65534:65534:0755:/var/data"
    volumes:
      - ./prometheus/data:/var/data

  prometheus:
    image: prom/prometheus:v2.17.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus/data
    depends_on:
      - volumes-provisioner
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.size=1TB' #max 1 TB storage
      - '--storage.tsdb.retention.time=30d' #max 30 days storing
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.7.2
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-test}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
