version: "3"
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            PGDATA: ${PGDATA}
        ports:
            - 5432:5432
        volumes:
            - ${postgres_data}:/${PGDATA}
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - ${pgadmin_data}:/var/lib/pgadmin
        ports:
            - 80:80
